language: java
jdk:
  - openjdk7
  - openjdk8
  - openjdk9
  - openjdk10
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11
install: mvn install -Dgpg.skip
after_success:
  - mvn clean test jacoco:report coveralls:report